GET http://localhost:3000/api/digitaldocs

###

POST http://localhost:3000/api/digitaldocs
Content-Type: application/json

{
    "name": "New text",
    "textContent": "This is some text...",
    "textColor": "orange",
    "backgroundColor": "black"
}


###

PUT http://localhost:3000/api/digitaldocs
Content-Type: application/json

{
    "_id": 3,
    "name": "Updated text",
    "textContent": "This is some text 3...",
    "textColor": "red",
    "backgroundColor": "black",
    "date": ""
}


###

DELETE  http://localhost:3000/api/digitaldocs
Content-Type: application/json

{
    "_id": 3
}